### PR TITLE
merge changes for pull request created

### PR DESCRIPTION
**Pull request by vairamsvsjdo**

### CODE REVIEW

**Comment by vairamsvsjdo** [comment]
@Preetha2019 https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

**Comment by vairamsvsjdo** [comment]
why were all these files deleted

**Comment by Preetha2019** [comment]
In order to commit all .c files i use"git add ." command. But, I only move .c files into stage changes and then commit. Unfortunately all files are committed on github. So, I deleted the files that aren't  .c file

**Comment by vairamsvsjdo** [comment]
Is dump2.c exists or equivalent file exists still in git?
https://github.com/vairamsvsjdo/samplec/pull/1/commits/8a37f095f502b3700a0b898fa2bd27e117d8b01f

**Comment by Preetha2019** [comment]
Here, -dump2.c, -justify.c content of these files already present in dump.c, justify.c. So, I deleted these files and to execute make file i created a file and instantly i put name as amma.c. Thus, this is unnecessary  so, i deleted this file

**Pull request merged**
